import type { Metadata } from 'next';
import '@/config/globals.css';
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';
import { FontClassNames } from '@/config/font';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: 'Create kitedev blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full scroll-smooth' suppressHydrationWarning>
      <body className={`${FontClassNames} flex min-h-screen flex-col`}>
        <ThemeProvider>
          <Header />
          <main className='flex flex-1 flex-col'>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
