import type { Metadata } from 'next';
import '@/config/globals.css';
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';

export const metadata: Metadata = {
  title: 'Create kitedev blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full scroll-smooth'>
      <body>
        <Header />
        <main className='mt-[64px] flex flex-1 flex-col'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
